"""empty message

Revision ID: 3658b1d684dc
Revises: ba7c9bcfdf96
Create Date: 2023-12-22 16:22:51.936272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3658b1d684dc'
down_revision: Union[str, None] = 'ba7c9bcfdf96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
